services:
  bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MODEL=${MODEL}
      - TOKEN_UNIT_PRICE=${TOKEN_UNIT_PRICE}
      - EXCHANGE_RATE=${EXCHANGE_RATE}
      - CURRENCY_UNIT=${CURRENCY_UNIT}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - GCP_SEARCH_API_KEY=${GCP_SEARCH_API_KEY}
      - GOOGLE_CUSTOM_SEARCH_CX=${GOOGLE_CUSTOM_SEARCH_CX}
    restart: always