services:
  bot:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MODEL=${MODEL}
      - INPUT_TOKEN_PRICE_PER_1M=${INPUT_TOKEN_PRICE_PER_1M}
      - OUTPUT_TOKEN_PRICE_PER_1M=${OUTPUT_TOKEN_PRICE_PER_1M}
      - EXCHANGE_RATE=${EXCHANGE_RATE}
      - CURRENCY_UNIT=${CURRENCY_UNIT}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - SEARCH_CONTEXT_SIZE=${SEARCH_CONTEXT_SIZE}
    restart: always